### ISSUE TITLE
Failed to mount into fi--san03

### ISSUE THREAD

**Issue by DAChristina** [mrc-ide/hipercow#129]
Hello.

This is the first time I use Hipercow. The issue exist since the first time I tried to connect my computer to the network, when my computer cannot mount to fi--san03:

```
ron@lmos:~$ sudo mount -a
mount error: could not resolve address for fi--san03: Unknown error
mount error: could not resolve address for fi--didef3: Unknown error
```

Details:
1. #####################################################################################################
I am using Linux Mint and I have installed zscaler. I tried and edit my fstab file into two version: (1) the one without <noauto> comment and (2) the other one with <noauto> comment. Here comes the snippet of my code without <noauto> comment:

```
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/sdb3 during installation
UUID=be2313de-949b-4f51-90ff-f461febc909e /               ext4    errors=remount-ro 0       1
# /boot/efi was on /dev/sda5 during installation
UUID=03EA-BEDD  /boot/efi       vfat    umask=0077      0       1
# /home was on /dev/sdb4 during installation
UUID=8c9d0955-755e-49e7-a63d-8bfac8b70b9e /home           ext4    defaults        0       2

//fi--san03/homes/dac23 /home/ron/net/home cifs uid=1000,gid=1000,credentials=/home/ron/.smbcredentials,domain=DIDE,sec=ntlmssp,iocharset=utf8, 0  0
//fi--didef3/tmp /home/ron/net/temp cifs uid=1000,gid=1000,credentials=/home/ron/.smbcredentials,domain=DIDE,sec=ntlmssp,iocharset=utf8, 0  0


# swap was on /dev/sda1 during installation
UUID=0b3fcf65-08a4-4e54-acb0-a4409bde1a75 none            swap    sw              0       0
# swap was on /dev/sdb1 during installation
UUID=be34f9b6-51ff-4f1e-95dc-7a08a531186b none            swap    sw              0       0
```

2. #####################################################################################################
I also create a credential file (and make sure the location of the file is in my /home/ron/) and set this to be chmod 600:
```
ron@lmos:~$ sudo cat ~/.smbcredentials
username=dac23
password=************
```
![image](https://github.com/mrc-ide/hipercow/assets/155730764/d675b096-793d-4a01-9ae8-0290cd2e030c)

Would someone be willing to help me?

**Comment by weshinsley** [comment]
This is not an issue specific to hipercow; this is just a problem mounting DIDE shares from linux.

The Teams channels are better ways of getting support (Programming or Cluster - we'll be able to help more easily from there)

At a quick guess, while you've installed zscaler, have you definitely logged into that correctly before trying the mount? Perhaps also try using fully qualifiied paths, eg, `fi--san03.dide.ic.ac.uk` instead of just `fi--san03` too (as in the hipercow docs - https://mrc-ide.github.io/hipercow/articles/windows.html - see linux section). Also check you've got the `cifs-utils` package installed.

**Comment by DAChristina** [comment]
[like]  Christina, Dewi A reacted to your message:
________________________________
