### ISSUE TITLE
there is no package called ‘pkgdepends’

### ISSUE THREAD

**Issue by jeffeaton** [mrc-ide/hipercow#142]
I'm just doing a first install of `hipercow`.

When I get to provisioning package:
```
hipercow_provision(method = "pkgdepends", refs = "local::./first90_1.6.11.tar.gz")
```

The function is failing with a message `there is no package called ‘pkgdepends’`:

```
Error in `pkgdepends_parse()`:
! Failed to parse some package references
✖ local::./F90utils_0.1.11.tar.gz: there is no package called ‘pkgdepends’
Run `rlang::last_trace()` to see where the error occurred.
```

This is easy enough to resolve by installing `pkgdepends` and re-running. But it left me wondering if there is a dependency missing somewhere.

Please go ahead and close issue if this is intended behavviour.

**Comment by weshinsley** [comment]
So to be clear, this is a local issue - pkgdepends is needed on your local machine in order for the provision to work, which is not very intuitive. We could improve this a bit.
